### ISSUE TITLE
有使用文档吗

### ISSUE THREAD

**Issue by Deeyu** [ano-ui/ano-ui#20]

**Comment by nei1ee** [comment]
暂时还没有，可以通过 `playground` 查看一些详细用法。

**Comment by lentg** [comment]
vercel的二级域名打不开，建议绑定个域名

**Comment by nei1ee** [comment]
> vercel的二级域名打不开，建议绑定个域名

最近 vercel 访问确实有些问题，绑定其他域名用处也不大，我也没有服务器，换个🪜可能好点。

**Comment by lentg** [comment]
我有个delii.cn的，你发出来，我来cname
