### ISSUE TITLE
Can only be used in cli projects? With usge's installation, the styles don't work

### ISSUE THREAD

**Issue by qixiaobro** [ano-ui/ano-ui#24]
Can only be used in cli projects? With usge's installation, the styles don't work
<img width="982" alt="截屏2023-01-18 下午1 27 01" src="https://user-images.githubusercontent.com/34623348/213091493-f6137c67-63e4-47b2-a922-cdeb13dd28fa.png">

**Comment by nei1ee** [comment]
Yes, it can only be used in cli project because it depends on `vite` and `UnoCSS`. And the component library does not export the `style.css` file now.

**Comment by qixiaobro** [comment]
ok
