### ISSUE TITLE
给按钮加margin-bottom,并没有撑开底部的内容

### ISSUE THREAD

**Issue by chenjz08** [ano-ui/ano-ui#28]
![image](https://user-images.githubusercontent.com/35839751/228453017-6cf77c0a-f485-4112-a793-38ebdeda65aa.png)

![image](https://user-images.githubusercontent.com/35839751/228452660-c0e6a25d-f734-46ca-8de3-5eaf76155594.png)
![image](https://user-images.githubusercontent.com/35839751/228453095-f300f417-8267-4dc2-9fe7-1d8e82b5b70a.png)

**Comment by nei1ee** [comment]
在微信小程序中组件外面会包裹一层`<a-xx is="xx"></a-xx>`这个上面的样式不会生效，如果想要自定义组件样式，有`cc`和`cs`属性，对应class和style，`<AButton cc="mb-24rpx" block></AButton>`

**Comment by chenjz08** [comment]
嗯嗯
