### ISSUE TITLE
refactor: 按组件划分、为每个组件提供完整的 unocss 配置

### ISSUE THREAD

**Issue by hairyf** [ano-ui/ano-ui#49]
在 preset 中，每个组件仅限于 shortcuts 的使用，局限性太大，这意味着每个组件只能添加 shortcuts 相关的规则

而实际往往有更多的内容需要添加在其他配置中：

```ts
    rules: [
      ['a-badge-bottom-dot', { bottom: 'calc(100% - 8rpx)' }],
      ['a-badge-bottom', { bottom: 'calc(100% - 18rpx)' }],
      ['a-badge-animation', {
        'animation-name': 'badge-wave-spread',
        'animation-timing-function': 'cubic-bezier(0, 0, 0.2, 1)',
        'animation-iteration-count': 'infinite'
      }]
    ],
    safelist: {
      'a-badge-wave': 'a-badge-animation duration-2s delay-1s'
    },
    preflights: [
      {
        getCSS: () => `
        @keyframes badge-wave-spread {
          from {
            box-shadow: 0 0 0.10rpx 0px rgba(var(--ano-c-context),var(--un-bg-opacity));
            opacity: 0.6;
          }
          to {
            box-shadow: 0 0 1rpx 9rpx rgba(var(--ano-c-context),var(--un-bg-opacity));
            opacity: 0;
          }
        }
        `
      }
    ]
  }
```

**Comment by nei1ee** [comment]
赞同🤣

**Comment by nei1ee** [comment]
~~一些简单的写到组件源代码里怎么样？~~
待解决问题：
- 组件开发友好，样式热更新
- 在使用时组件样式按需加载

**Comment by hairyf** [comment]
一些简单的样式可以适当的编写在组件当中，这是 vue 的一个非常便捷的特性，同时使用组件时能够保证按需加载。

我们应该尽量使用 @apply/--at-apply（unocss 命令）的标识符，但也可能会导致我们过分依赖于 unocss，从而导致后续导出样式的困难。

我们后续可以继续探讨如何进一步编译 <style> 中的代码（尝试在 [uni-tsc#1](https://github.com/hairyf/uni-tsc/issues/1) 中支持）

总的来说，的确将所有配置提供给组件反倒不利于单一原则，unocss 方面，我们应该提供的更加通用的属性，而不是过多组件的 shortcuts、rules、或其他规则。

**Comment by nei1ee** [comment]
如果使用小程序不支持的选择器，我们需要使用 `@unocss/cli` 打包生成 H5 和小程序相应的 `styles` https://github.com/ano-ui/ano-ui/pull/51/commits/71cbecaecf5a3553851ce57a1a4d18c2110324b2 ，同时还需要提供两种组件源代码。但是如果组件 `<style>` 里面有 `@apply/--at-apply` 无法生成，在使用时还是需要使用`unocss`。

**Comment by hairyf** [comment]
你的意思是 @apply/--at-apply 无法被打包吗？ 如果是这样的话，是一个 unocss 错误，还是有意设计？

**Comment by nei1ee** [comment]
> 你的意思是 @apply/--at-apply 无法被打包吗？ 如果是这样的话，是一个 unocss 错误，还是有意设计？

`@apply/--at-apply` 里面的每个类可以生成，应该是有意设计，这里如果被打包需要改变<style>内源代码。

**Comment by hairyf** [comment]
我们可以使用 transformDirectives 编译 style，这是将来可以实现的

```ts
const uno = createGenerator({ ...config })
const code = new MagicString(css)
await transformDirectives(code, uno, { ...options }, 'xxx.vue.css')
code // transform code
```

现在先让我们从使用 @apply 开始

**Comment by zguolee** [comment]
有使用，不知道是不是操作不对。
```ts
export default defineConfig({
  cli: {
    entry: {
      patterns: ['components/**/*.{vue,ts}'],
      outFile: 'dist/styles.mp.css',
    },
  },
  presets: [
    ...
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
    transformerAttributify({ ignoreAttributes: ['block'] }),
    transformerApplet(),
  ],
}
```
