### ISSUE TITLE
 refactor: ano-ui  separate monorepo

### ISSUE THREAD

**Issue by hairyf** [ano-ui/ano-ui#62]
ano-ui 不应该包含所有 deps，这将导致安装 ano-ui 变为及其冗余，ano-ui 仅包含 ui 与组件配置的实现。

1. 解决 unocss 配置高亮问题(.vscode/settings.json)：

```json
  "unocss.root": [
    "packages/component",
    "packages/playground"
  ],
```
```
pacakges
- ano-ui
  ....
- component
  - unocss.config.ts
  - ....
- playground
  - unocss.config.ts
  - ....
```

2. docs、polp、eslint、build.... 相关处理 deps 由主包安装（ano-ui-monorepo）

**Comment by nei1ee** [comment]
之前从 `monorepo` 换成现在的的原因是因为不能开发时候热更新，用相对路径自动引入 `windows` 上又有问题，不知道有没有好的方式可以解决这些问题。

**Comment by hairyf** [comment]
开发使用原始路径，通过 publishConfig 替换原始路径：

ano-ui package.json：

```json
{
  "name": "ano-ui",
  "main": "src/index.ts",
  "publishConfig": {
      "main": "./dist/index.js",
      "linkDirectory": false
   }
}
```

这在大型 monorepo 项目非常实用，减少了很多不必要的编译。

我有很多基于此模式的类似项目，也许你可以参考一下：

- https://github.com/hairyf/hairylib
- https://github.com/hairyf/unoverlays
- https://github.com/hairyf/u-draw

**Comment by nei1ee** [comment]
> 开发使用原始路径，通过 publishConfig 替换原始路径：
> 
> ano-ui package.json：
> 
> ```json
> {
>   "name": "ano-ui",
>   "main": "src/index.ts",
>   "publishConfig": {
>       "main": "./dist/index.js",
>       "linkDirectory": false
>    }
> }
> ```
> 
> 这在大型 monorepo 项目非常实用，减少了很多不必要的编译。
> 
> 我有很多基于此模式的类似项目，也许你可以参考一下：
> 
> * https://github.com/hairyf/hairylib
> * https://github.com/hairyf/unoverlays
> * https://github.com/hairyf/u-draw

一会我看看🥳
在这个分支 [refactor](https://github.com/ano-ui/ano-ui/tree/refactor) 我还在做一些修改，主要一些小bug和换成中文。

**Comment by Skiyee** [comment]
vite4 更新至 vite5 后更改组件源码时，无法正常触发hmr？二位大佬有什么想法？
