### ISSUE TITLE
为啥input默认输入就是类似password

### ISSUE THREAD

**Issue by brandonxiang** [ano-ui/ano-ui#8]
都打码了

**Comment by brandonxiang** [comment]
https://github.com/ano-ui/ano-ui/blob/9ae8f3147e6743804fbf98a5adc36b7d4c6dc018/packages/components/AInput/AInput.vue#L69

大部分应该都不是password才对

**Comment by nei1ee** [comment]
请问是使用的哪一个版本，这个问题之前应该已经被修复了。

**Comment by brandonxiang** [comment]
0.0.11

**Comment by nei1ee** [comment]
那需要更新一下了，0.1.1修复了问题。🥲
