### ISSUE TITLE
微信小程序中不支持 backgroun : rgb(var(--ano-c-context) / var(--un-bg-opacity)) 这种透明度的写法，我应该怎么处理呢？

### ISSUE THREAD

**Issue by im55cc** [ano-ui/ano-ui#84]

**Comment by nei1ee** [comment]
可以使用自定义属性custom-class和custom-style修改

**Comment by im55cc** [comment]
我复用了你仓库 https://github.com/ano-ui/ano-ui/tree/main/example 下的 vite.config.ts h还有 uno.config.ts 这个 按钮背景样式的问题还是存在，这是我测试的 demo https://github.com/im55cc/ano-ui-test ，能帮忙提供一些思路吗？谢谢！

**Comment by im55cc** [comment]
我大概找到问题了，应该是 unocss 升级导致不兼容， https://github.com/unocss/unocss/commit/5c3d02d5

https://github.com/ano-ui/ano-ui/blob/7fe18c4e68a2fcb40106c84cf18e770162e660c8/packages/preset/src/rules.ts#L10C42-L10C42 ，如果我没猜错的话，应该是这行代码导致的不兼容，等晚些时候，我来尝试着提交一个pr

**Comment by nei1ee** [comment]
确实是这个问题
