### ISSUE TITLE
uno.config.ts文件里【presetApplet, presetRemRpx, transformerApplet】是起什么作用啊？

### ISSUE THREAD

**Issue by elarbor** [ano-ui/ano-ui#87]
![image](https://github.com/ano-ui/ano-ui/assets/43592730/10a141af-00a9-4f61-83b4-cbf4c416c3d8)

**Comment by nei1ee** [comment]
因为unocss不能直接用于小程序，这里是一些转换插件，可以从unocss-applet了解更多信息。
