### ISSUE TITLE
iconify怎么使用啊

### ISSUE THREAD

**Issue by elarbor** [ano-ui/ano-ui#89]
安装了`@iconify-json/tabler `，按照 `i-` 开头[图标名](https://icones.js.org/)渲染不出来啊
![image](https://github.com/ano-ui/ano-ui/assets/43592730/3a5c9b91-57c3-419b-a0a5-95ea2aae91a0)

**Comment by nei1ee** [comment]
看一下unocss.config.ts有没有presetIcon

**Comment by elarbor** [comment]
> 看一下unocss.config.ts有没有presetIcon
有
![image](https://github.com/ano-ui/ano-ui/assets/43592730/1acbaa5c-600f-49cf-9ad9-dc707b37ce38)

**Comment by nei1ee** [comment]
请参考unocss使用说明
